apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gerarbem-prod
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/gerarbem`)
      kind: Rule
      services:
        - name: nginx
          port: 80
      middlewares:
        - name: gerarbem-prod-strip-prefix
