apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>gerarbem</title>
    </head>
    <body style="font-family: Arial; text-align: center; margin-top: 80px;">
      <h1>gerarbem</h1>
      <p>Aplicação provisionada via ArgoCD + GitOps.</p>
      <p>Ambiente: homolog</p>
    </body>
    </html>
